### ISSUE TITLE
Arctis 9

### ISSUE THREAD

**Issue by ateee0907** [atagulalan/arctis-battery-percentage#10]
Hey!

First of all thanks for this script.

I have brand new Arctis 9 headset.

Does this script support it ? Or only the older version of this headsets?

Thank you in advance.

**Comment by atagulalan** [comment]
Hello @ateee0907 

This script does not support it yet, but you can help me to add Arctis 9 support.

Create a file named `report.js` inside project directory and put this code inside:
```
var HID = require('node-hid')
HID.setDriverType('libusb')
var devices = HID.devices()
console.log(devices)
```

Open command prompt and type `node report.js`.

Send output here so I can analyze and add Arctis 9.

Thank you.

**Comment by ateee0907** [comment]
I would like to help you, but i have some problem. I created the report.js file with the content you shared with me but I cannot run it, cause CMD said cannot find module 'node-hid'. I have tried to install it with npm install node-hid, but it was not successful. There are a lot of error message. Could you help me please how to fix this in order to run report.js ? :)

**Comment by ateee0907** [comment]
[report.txt](https://github.com/atagulalan/arctis-battery-percentage/files/5294147/report.txt)
Here you can find the report, i deleted the unnecessary things from it.

Thanks a lot for adding arctis 9 as well.

**Comment by atagulalan** [comment]
For extra confirmation, could you turn on the headset and try these steps again?

Thank you.

**Comment by ateee0907** [comment]
Sure thing, Now the headset is turned on and charging.

Please see the report here:
[report2.txt](https://github.com/atagulalan/arctis-battery-percentage/files/5298097/report2.txt)

**Comment by atagulalan** [comment]
Ok, one last thing.

Could you turn off the device, unplug the charging cable and turn on the headset?
I am sorry to bother you this way, but none of those devices listed matches the criteria.

Thank you.

**Comment by ateee0907** [comment]
No problem, I am happy to help you, since you are helping me as well.

I attached the new file, now the headset is on and unplugged. And I left everything on it, hope this will help now.

[report.txt](https://github.com/atagulalan/arctis-battery-percentage/files/5298402/report.txt)

**Comment by atagulalan** [comment]
I added Arctis 9 Support, but i am still not sure it works. Can you give it a try?
PS: If it is not working correctly, try to unplug transreciever and plug it in again.

Thank you.

**Comment by ateee0907** [comment]
I tried it, but it is not working, I unplugged the reciever and plug it in, but did not help.

**Comment by ateee0907** [comment]
![image](https://user-images.githubusercontent.com/72019801/94551883-5287b300-0256-11eb-926a-9bd67dc31eb7.png)

But it is not writiing anything on console. Isn't it strange?

**Comment by atagulalan** [comment]
Could you try `node ./percentage.js` inside project directory?

**Comment by ateee0907** [comment]
It's not working as well

![image](https://user-images.githubusercontent.com/72019801/94552794-c24a6d80-0257-11eb-85d5-ddab1d1b75eb.png)

**Comment by atagulalan** [comment]
Do you have SS Engine installed?

**Comment by ateee0907** [comment]
yes I have

**Comment by atagulalan** [comment]
1) Connect the headset
2) Make sure SS Engine shows the headset remeaning icon
3) `node ./report.js` in main directory
4) Check devices has 4152 vendor id 
5) One of them needs to have usagePage not defined as 1
6) If none match, try to replug the device, replug it in another usb port, try charging state, wireless state, restart your pc and try again and check devices again (3)
7) If something matches, get productId and please post it here.
![image](https://user-images.githubusercontent.com/8681330/94553334-0a21c280-0261-11eb-835f-fea0192cefc8.png)

PS: If they changed communication message to check the percentage (which i doubt), we have some more work to do.

**Comment by ateee0907** [comment]
{
    vendorId: 4152,
    productId: 4802,
    path: '\\\\?\\hid#vid_1038&pid_12c2&mi_01#b&2b1a647a&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'SteelSeries Arctis 9',
    release: 113,
    interface: 1,
    usagePage: 12,
    usage: 1
  },
  {
    vendorId: 4152,
    productId: 4802,
    path: '\\\\?\\hid#vid_1038&pid_12c2&mi_00#b&17ea483c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'SteelSeries Arctis 9',
    release: 113,
    interface: 0,
    usagePage: 65472,
    usage: 1
  },
  {
    vendorId: 4152,
    productId: 4804,
    path: '\\\\?\\hid#vid_1038&pid_12c4&mi_05#b&37e6ff42&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    serialNumber: '000000000000',
    manufacturer: 'SteelSeries',
    product: 'SteelSeries Arctis 9',
    release: 3,
    interface: 5,
    usagePage: 12,
    usage: 1
  },

  {
    vendorId: 4152,
    productId: 4802,
    path: '\\\\?\\hid#vid_1038&pid_12c2&mi_02#b&2afb6b1&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'SteelSeries Arctis 9',
    release: 113,
    interface: 2,
    usagePage: 65280,
    usage: 1
  },
Please check this, hope this helps

**Comment by ateee0907** [comment]
This one is appearing when its charging.
{
    vendorId: 4152,
    productId: 4800,
    path: '\\\\?\\hid#vid_1038&pid_12c0&mi_00#a&a4888bd&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
    manufacturer: 'SteelSeries',
    product: 'SteelSeries Arctis 9',
    release: 256,
    interface: 0,
    usagePage: 65472,
    usage: 1

**Comment by AshAb12** [comment]
I tried the update as soon as it was pushed out and was hoping it would be updated to actually work but its been 2 weeks. Are there plans to add proper support or is it too much work? I own an arctis 9 so if there is any device information I can provide I'm willing to help out. My friend uses this project for his arctis 7s and he said it works great. Looking forward to hopefully enjoy this on my 9s.

**Comment by atagulalan** [comment]
Hey @AshAb12,
Thank you for your message. I am currently planning to add Arctic 9 support, but unfortunately I do not have the device and have some problems finding device ID. 
You can contribute to this project. We can arrange a meeting. E-mail me for details: ata@xava.me
Thank you.

**Comment by ateee0907** [comment]
Hi Guys,

Please let me know if you have any improvement in this case.

**Comment by atagulalan** [comment]
Hey @ateee0907,

I think communication between the dongle and the device has changed. Initially, I was sending [0x06, 0x18] to the device.

You can check out this blog to replicate the process: [Reverse engineering : récupérer le niveau de batterie du casque sans fil SteelSeries Arctis 7](https://blog.flozz.fr/2020/05/25/reverse-engineering-recuperer-le-niveau-de-batterie-du-casque-sans-fil-steelseries-arctis-7/)

Thank you.

**Comment by ateee0907** [comment]
Hi @atagulalan,

Thanks for your response, I really appreciate it.

Unforntunately, I have to say that somehow it's still doesn't work for me :(

I don't really know what could be the problem.
