### ISSUE TITLE
Is there way to get some kind of video tutorial for this?

### ISSUE THREAD

**Issue by Porvarinen** [atagulalan/arctis-battery-percentage#14]
I am kinda beginner with all this node stuff and while i took a while to research answers to install those modules right way i didnt get it to work. I would be really happy to learn how to do this with more depth on install tutorial and it would be good for other beginners that are trying to get this awesomeness to work.

**Comment by atagulalan** [comment]
You can check out this issue: https://github.com/atagulalan/arctis-battery-percentage/issues/7#issuecomment-697273466
Thank you.
