### ISSUE TITLE
Feature request: Include SteelSeries Wireless Mouse

### ISSUE THREAD

**Issue by DPaaske** [atagulalan/arctis-battery-percentage#27]
Hi man,

Great project! Cool to see people volunteer their time to adding features SteelSeries neglect.
 
Do you think it would be possible to expand on the functionality your project to also include wireless mice? 
I have a Rival 650 Wireless, and apparently SteelSeries think using the scroll wheel as the only battery indicator was sufficient. 

I would love to be able to display the battery level on the display of my Apex Pro keyboard.

**Comment by Piipperi** [comment]
This would be nice, for my Aerox 3 Wireless (Ghost) the product ID is 0x1838.
I tried adding it myself to the .js but it just results `Error: Cannot write to Arctis Wireless device. Please replug the device.`

But I'm glad to know that this even works on macOS to an extent, seeing SteelSeries "addons" work on macOS is very rare.

**Comment by atagulalan** [comment]
Hi,

I'm sorry, but I don't intend to devote time to this project anymore. SteelSeries changed the way wireless communication works after Arctis 9.

If you are tech-savvy, this might help: https://github.com/atagulalan/arctis-battery-percentage/issues/10#issuecomment-708294419

Thank you.
