### ISSUE TITLE
Not recognising headset

### ISSUE THREAD

**Issue by chaoticPT** [atagulalan/arctis-battery-percentage#4]
Headset plugged and working but still getting "Your SteelSeries Arctis 7 device's battery percentage is 0" on cmd and "Please connect your SteelSeries Wireless Device first" on notifications panel.

**Comment by atagulalan** [comment]
Could you try replugging your headset adapter?

**Comment by chaoticPT** [comment]
I just saw it now and before replugging i tried to run the command again and worked(i haven't turned off my pc since i posted the issue)

**Comment by atagulalan** [comment]
Hello,
Could you inform me when you restart your PC?
Thank you.
