### ISSUE TITLE
I need more help with this :(

### ISSUE THREAD

**Issue by iiB3An** [atagulalan/arctis-battery-percentage#7]
I have no idea how to install this, please help :(

**Comment by atagulalan** [comment]
Hello,

I am glad you asked. I know the documentation is not provided and some of us struggle even to open it.

First, install Node.js on your machine. I assume you are using Windows.

Link: https://nodejs.org/en/download/
Guide: https://phoenixnap.com/kb/install-node-js-npm-on-windows

After this, open your command prompt and install package globally by typing

`npm i -g arctis-battery-percentage`

after you install npm package, all you need to type in command line is

`arctis-battery`

and you are ready to go.

If you want system tray icon, you can follow the guide on this issue: https://github.com/atagulalan/arctis-battery-percentage/issues/6#issuecomment-640131605

You have to change branch to TrayIcon and Download the code on GitHub.

If you have any more questions, I am ready to help.

Thank you.
