### ISSUE TITLE
Package as distributable release

### ISSUE THREAD

**Issue by s7726** [atagulalan/arctis-battery-percentage#8]
Would be super convenient if this all got wrapped up into something that was distributable to end users without having to install a full node dev environment.

https://dev.to/jochemstoel/bundle-your-node-app-to-a-single-executable-for-windows-linux-and-osx-2c89

**Comment by atagulalan** [comment]
Please refer to [richrace/arctis-monitor](https://github.com/richrace/arctis-monitor)
